version: '2'
services:

  # note; symlink docker-compose.development.yml to
  # docker-compose.override.yml when developing.

  web:
    build: .
    image: phylowebtools
    environment:
      FLASK_APP: /app/app.py
    command: /bin/bash -c ". /venv/bin/activate && flask run"
    ports:
      - 5000:5000
    restart: unless-stopped